find_package(SDL2 REQUIRED)
if(SDL2_FOUND)
    message(STATUS "Found SDL2: " ${SDL2_LIBRARIES} " " ${SDL2_INCLUDE_DIR})
    add_definitions(-DGUI -DSDL2)
    include_directories(${SDL2_INCLUDE_DIR})
endif()
